### ISSUE TITLE
s2-v0.0.4-node-v93-linux-x64.tar.gz does not exist

### ISSUE THREAD

**Issue by TaimuJietai** [radarlabs/s2#53]
npm ERR! node-pre-gyp http 404 https://node-s2-binaries.s3.amazonaws.com/s2/v0.0.4/Release/s2-v0.0.4-node-v93-linux-x64.tar.gz

https://node-s2-binaries.s3.amazonaws.com/

**Comment by TaimuJietai** [comment]
```
npm ERR! code 1
npm ERR! path xxx/node_modules/@radarlabs/s2
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! make: Entering directory `xxx/node_modules/@radarlabs/s2/build'
npm ERR!   CXX(target) Release/obj.target/s2/src/s2.o
npm ERR! make: Leaving directory `xxx/node_modules/@radarlabs/s2/build'
npm ERR! Failed to execute '/opt/node-v16.14.2-linux-x64/bin/node /opt/node-v16.14.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/xxx/node_modules/@radarlabs/s2/lib/binding/Release/node-v93-linux-x64/s2.node --module_name=s2 --module_path=/xxx/node_modules/@radarlabs/s2/lib/binding/Release/node-v93-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.14.0
npm ERR! node-pre-gyp info using node@16.14.2 | linux | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/xxx/node_modules/@radarlabs/s2/lib/binding/Release/node-v93-linux-x64/s2.node" (not found)
npm ERR! node-pre-gyp http GET https://node-s2-binaries.s3.amazonaws.com/s2/v0.0.4/Release/s2-v0.0.4-node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://node-s2-binaries.s3.amazonaws.com/s2/v0.0.4/Release/s2-v0.0.4-node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://node-s2-binaries.s3.amazonaws.com/s2/v0.0.4/Release/s2-v0.0.4-node-v93-linux-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for @radarlabs/s2@0.0.4 and node@16.14.2 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://node-s2-binaries.s3.amazonaws.com/s2/v0.0.4/Release/s2-v0.0.4-node-v93-linux-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.8 found at "/bin/python3"
npm ERR! gyp info spawn /bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/node-v16.14.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/xxx/node_modules/@radarlabs/s2/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/node-v16.14.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/node-v16.14.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/xxx/node_modules/@radarlabs/s2',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: error: unrecognized command line option ‘-std=gnu++14’
npm ERR! g++: error: unrecognized command line option ‘-std=c++14’
npm ERR! make: *** [Release/obj.target/s2/src/s2.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/node-v16.14.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 3.10.0-862.el7.x86_64
npm ERR! gyp ERR! command "/opt/node-v16.14.2-linux-x64/bin/node" "/opt/node-v16.14.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/xxx/node_modules/@radarlabs/s2/lib/binding/Release/node-v93-linux-x64/s2.node" "--module_name=s2" "--module_path=/xxx/node_modules/@radarlabs/s2/lib/binding/Release/node-v93-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /xxx/node_modules/@radarlabs/s2
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/opt/node-v16.14.2-linux-x64/bin/node /opt/node-v16.14.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/lib/jenkins/workspace/lifekh-mp-nodejs-mobile-app-composition-sit/node_modules/@radarlabs/s2/lib/binding/Release/node-v93-linux-x64/s2.node --module_name=s2 --module_path=/xxx/node_modules/@radarlabs/s2/lib/binding/Release/node-v93-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/xxx/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Linux 3.10.0-862.el7.x86_64
npm ERR! node-pre-gyp ERR! command "/opt/node-v16.14.2-linux-x64/bin/node" "/xxx/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /xxx/node_modules/@radarlabs/s2
npm ERR! node-pre-gyp ERR! node -v v16.14.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.14.0
npm ERR! node-pre-gyp ERR! not ok
```

**Comment by jkao** [comment]
0.0.5 should have the appropriate binaries if you update it
